Integrated eq-smoke-tests into pipeline
ONSdigital/eq-deploy pull request #13
Opened 2018-01-10 14:39 UTC by jonnyshaw89

Integrated eq-smoke-tests into pipeline
Added failure notifications via slack

## To Review
See that the smoke tests are being run as part of the pipeline.
http://concourse.dev.eq.ons.digital/teams/main/pipelines/eq

2018-01-10 18:02 UTC, ajmaddaford requested changes

2018-01-10 18:02 UTC, ajmaddaford commented on build_containers/author-build.dockerfile
> +    && apt-get install -y --allow-unauthenticated nodejs yarn google-chrome-stable
Any reason not to add the [Google GPG key](https://www.google.com/linuxrepositories/) so we don't need to use `--allow-unauthenticated `?

2018-01-10 18:02 UTC, ajmaddaford commented on eq.yml
> +  serial_groups: [staging-deploy, staging-accessibility-tests, staging-performance-tests, staging-security-tests, staging-destroy]
We should remove references to accessibility, performance and security tests if they don't exist yet

2018-01-11 09:53 UTC, MIslam92 requested changes
Would there be any value changing the name of eq.yml to pipeline/eq-pipeline.yml as thats what is essentially is?

2018-01-11 09:59 UTC, jonnyshaw89 commented
@MIslam92 potentially but its very trivial

2018-01-11 13:07 UTC, ajmaddaford approved these changes

2018-01-11 13:37 UTC, MIslam92 approved these changes
"Squishy Squashy"

2018-01-11 13:50 UTC, merged