Deploy author redis to prod
ONSdigital/eq-deploy pull request #86
Opened 2019-07-16 14:15 UTC by tgandrews

This builds on #85 and requires it to be merged first

2019-07-16 14:24 UTC, samiwel requested changes

2019-07-16 14:24 UTC, samiwel commented on deploy.yml
> +              terraform apply
I think this should be plan instead of apply

2019-07-18 08:40 UTC, samiwel approved these changes
LGTM

2019-07-18 11:48 UTC, SamGodwin2 approved these changes

2019-07-18 13:00 UTC, merged